apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: artevier
spec:
  replicas: {{ (index .Values.services "frontend").replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ (index .Values.services "frontend").image }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ (index .Values.services "frontend").targetPort }}