apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: artevier
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: {{ (index .Values.services "order-service").port }}
      targetPort: {{ (index .Values.services "order-service").targetPort }}
      protocol: TCP