import { Injectable, signal } from '@angular/core';

export type DisplayLanguage = 'fr' | 'hu';

const LANGUAGE_STORAGE_KEY = 'cuisine_language';

const TRANSLATIONS: Record<DisplayLanguage, Record<string, string>> = {
  fr: {
    'header.brand': 'Maison Elegant',
    'header.subbrand': 'Maison Elegant',
    'header.home': 'Accueil',
    'header.catalog': 'Catalogue',
    'header.about': 'À propos',
    'header.contact': 'Contact',
    'header.login': 'Connexion',
    'header.register': "S'inscrire",
    'header.logout': 'Déconnexion',
    'header.dashboard': 'Tableau de bord',
    'header.admin': 'Admin',
    'home.heroTitle': 'Éviers artisanaux pour des intérieurs distingués',
    'home.heroLead': "Découvrez notre collection d'éviers faits main — chaque pièce est une œuvre d'art unique, conçue pour durer.",
    'home.browseCollection': 'Parcourir la collection',
    'home.ourStory': 'Notre histoire',
    'home.featured': 'Éviers en vedette',
    'home.shopByMaterial': 'Achetez par matériau',
    'home.bestSellers': 'Meilleures ventes',
    'home.testimonials': 'Ce que disent nos clients',
    'home.ctaTitle': 'Prêt à transformer votre espace ?',
    'home.ctaText': 'Des questions sur nos éviers artisanaux ? Notre équipe est là pour vous aider à trouver la pièce parfaite.',
    'home.ctaButton': 'Nous contacter',
    'about.title': 'À propos de Cuisine Elegante',
    'about.lead': 'Fondée à Portland, Oregon, Cuisine Elegante réunit des artisans d’exception et des foyers exigeants autour d’un marché de pièces fabriquées à la main.',
    'about.piece': 'Chaque évier de notre collection est créé par des artisans expérimentés qui apportent des décennies de savoir-faire à chaque pièce. Des éviers de ferme en cuivre martelé aux vasques en terre cuite finement émaillées, nos produits représentent l’excellence de l’art fonctionnel.',
    'about.missionTitle': 'Notre mission',
    'about.missionText': 'Préserver l’artisanat traditionnel tout en rendant les éviers de qualité artisanale accessibles aux intérieurs modernes. Nous croyons que l’évier — souvent oublié — doit être un point central qui raconte une histoire.',
    'about.qualityTitle': 'Engagement qualité',
    'about.bullet1': 'Chaque produit inspecté par notre équipe qualité',
    'about.bullet2': 'Directement sourcé auprès d’ateliers artisanaux vérifiés',
    'about.bullet3': 'Garantie de satisfaction de 30 jours sur tous les achats',
    'about.bullet4': 'Garantie à vie sur la fabrication pour certains modèles',
    'about.cta': 'Découvrir la collection',
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Une question ? Nous serions ravis de vous aider.',
    'contact.name': 'Nom',
    'contact.email': 'Email',
    'contact.subject': 'Sujet',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le message',
    'contact.emailInfo': 'support@cuisineelegante.com',
    'contact.phoneInfo': '+1 555 123 4567',
    'contact.addressInfo': '123 Rue du Studio, Portland, OR',
    'contact.sent': 'Message envoyé ! Nous vous répondrons bientôt.',
    'footer.title': 'Cuisine Elegante',
    'footer.description': 'Éviers faits main créés par des artisans experts. Chaque pièce raconte une histoire de savoir-faire, de qualité et de design intemporel.',
    'footer.quickLinks': 'Liens rapides',
    'footer.catalog': 'Catalogue',
    'footer.about': 'À propos',
    'footer.contact': 'Contact',
    'footer.rights': 'Tous droits réservés.',
    'auth.loginTitle': 'Bienvenue',
    'auth.loginSubtitle': 'Connectez-vous à votre compte Cuisine Elegante',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.errors.email': 'Un email valide est requis',
    'auth.errors.password': 'Le mot de passe est requis (min 6 caractères)',
    'auth.signingIn': 'Connexion en cours...',
    'auth.signIn': 'Se connecter',
    'auth.noAccount': 'Vous n’avez pas de compte ?',
    'auth.registerTitle': 'Créer un compte',
    'auth.registerSubtitle': 'Rejoignez Cuisine Elegante aujourd’hui',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.phoneOptional': 'Téléphone (optionnel)',
    'auth.phone': 'Téléphone',
    'auth.passwordHint': 'Min 6 caractères avec au moins un chiffre',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.errors.passwordMismatch': 'Les mots de passe ne correspondent pas',
    'auth.creatingAccount': 'Création du compte...',
    'auth.register': 'S’inscrire',
    'auth.haveAccount': 'Vous avez déjà un compte ?',
    'auth.currentPassword': 'Mot de passe actuel',
    'auth.newPassword': 'Nouveau mot de passe',
    'auth.address': 'Adresse',
    'profile.title': 'Mon profil',
    'profile.personalInfo': 'Informations personnelles',
    'profile.saving': 'Enregistrement...',
    'profile.saveChanges': 'Enregistrer les modifications',
    'profile.changePassword': 'Changer le mot de passe',
    'profile.updatingPassword': 'Mise à jour...',
    'profile.updatePassword': 'Mettre à jour le mot de passe',
    'profile.updated': 'Profil mis à jour avec succès.',
    'profile.passwordChanged': 'Mot de passe mis à jour avec succès.',
    'dashboard.welcome': 'Bienvenue',
    'dashboard.subtitle': 'Gérez votre compte et vos commandes',
    'dashboard.profileCard': 'Mon profil',
    'dashboard.ordersCard': 'Mes commandes',
    'dashboard.cartCard': 'Mon panier',
    'dashboard.recentOrders': 'Commandes récentes',
    'dashboard.orderLabel': 'Commande',
    'cart.title': 'Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.browseProducts': 'Parcourir les produits',
    'cart.remove': 'Supprimer',
    'cart.total': 'Total',
    'cart.checkout': 'Passer à la caisse',
    'checkout.title': 'Paiement',
    'checkout.shippingInfo': 'Informations de livraison',
    'checkout.fullName': 'Nom complet',
    'checkout.street': 'Adresse',
    'checkout.city': 'Ville',
    'checkout.state': 'État/Province',
    'checkout.zipCode': 'Code postal',
    'checkout.country': 'Pays',
    'checkout.placeOrder': 'Passer la commande',
    'checkout.orderSummary': 'Récapitulatif de commande',
    'language.fr': 'Français',
    'language.hu': 'Magyar',
  },
  hu: {
    'header.brand': 'Cuisine Elegante',
    'header.subbrand': 'Cuisine Elegante',
    'header.home': 'Kezdőlap',
    'header.catalog': 'Katalógus',
    'header.about': 'Rólunk',
    'header.contact': 'Kapcsolat',
    'header.login': 'Bejelentkezés',
    'header.register': 'Regisztráció',
    'header.logout': 'Kijelentkezés',
    'header.dashboard': 'Irányítópult',
    'header.admin': 'Admin',
    'home.heroTitle': 'Kézműves mosogatók kifinomult otthonokhoz',
    'home.heroLead': 'Fedezze fel kézzel készített mosogatók gyűjteményét — minden darab egyedülálló műalkotás, amely generációkig tart.',
    'home.browseCollection': 'Kollekció böngészése',
    'home.ourStory': 'Történetünk',
    'home.featured': 'Kiemelt mosogatók',
    'home.shopByMaterial': 'Anyag szerint',
    'home.bestSellers': 'Legkelendőbbek',
    'home.testimonials': 'Ügyfeleink mondták',
    'home.ctaTitle': 'Készen áll a tér átalakítására?',
    'home.ctaText': 'Kérdése van kézműves mosogatóinkkal kapcsolatban? Csapatunk segít megtalálni a tökéletes darabot.',
    'home.ctaButton': 'Lépjen kapcsolatba velünk',
    'about.title': 'A Cuisine Elegante-ről',
    'about.lead': 'A Cuisine Elegante kiváló kézműveseket és igényes otthonokat köt össze egy kézzel készített termékeket kínáló piactéren.',
    'about.piece': 'Minden mosogató szakértő kézművesek által készül, akik évtizedes tapasztalatukat öntik minden darabba. A kézzel kalapált rézfalusi mosogatóktól a gondosan mázolt tűzálló agyag mosdókig termékeink a funkcionális művészet csúcsát képviselik.',
    'about.missionTitle': 'Küldetésünk',
    'about.missionText': 'Helyreállítani a hagyományos kézművességet és elérhetővé tenni a modern otthonok számára a kézműves minőségű mosogatógépeket. Úgy gondoljuk, hogy a mosogató — amit gyakran figyelmen kívül hagynak — a tér központi eleme kell legyen, amely történetet mesél.',
    'about.qualityTitle': 'Minőség ígérete',
    'about.bullet1': 'Minden terméket ellenőriz minőségellenőrző csapatunk',
    'about.bullet2': 'Közvetlenül ellenőrzött kézműves műhelyektől származik',
    'about.bullet3': '30 napos elégedettségi garancia minden vásárlásra',
    'about.bullet4': 'Bizonyos darabokra élettartam garancia',
    'about.cta': 'Fedezze fel a kollekciót',
    'contact.title': 'Lépjen kapcsolatba velünk',
    'contact.subtitle': 'Van kérdése? Örömmel segítünk.',
    'contact.name': 'Név',
    'contact.email': 'Email',
    'contact.subject': 'Tárgy',
    'contact.message': 'Üzenet',
    'contact.send': 'Üzenet küldése',
    'contact.emailInfo': 'support@cuisineelegante.com',
    'contact.phoneInfo': '+1 555 123 4567',
    'contact.addressInfo': '123 Studio utca, Portland, OR',
    'contact.sent': 'Üzenet elküldve! Hamarosan válaszolunk.',
    'footer.title': 'Cuisine Elegante',
    'footer.description': 'Kézzel készített mosogatók szakértő kézművesektől. Minden darab időtlen designról, minőségről és mesterségről mesél.',
    'footer.quickLinks': 'Gyors linkek',
    'footer.catalog': 'Katalógus',
    'footer.about': 'Rólunk',
    'footer.contact': 'Kapcsolat',
    'footer.rights': 'Minden jog fenntartva.',
    'auth.loginTitle': 'Üdvözöljük',
    'auth.loginSubtitle': 'Jelentkezzen be Cuisine Elegante fiókjába',
    'auth.email': 'Email',
    'auth.password': 'Jelszó',
    'auth.errors.email': 'Érvényes email cím szükséges',
    'auth.errors.password': 'A jelszó szükséges (min 6 karakter)',
    'auth.signingIn': 'Bejelentkezés...',
    'auth.signIn': 'Bejelentkezés',
    'auth.noAccount': 'Nincs még fiókja?',
    'auth.registerTitle': 'Fiók létrehozása',
    'auth.registerSubtitle': 'Csatlakozzon a Cuisine Elegante-hez még ma',
    'auth.firstName': 'Keresztnév',
    'auth.lastName': 'Vezetéknév',
    'auth.phoneOptional': 'Telefon (opcionális)',
    'auth.phone': 'Telefon',
    'auth.passwordHint': 'Legalább 6 karakter, legalább egy szám',
    'auth.confirmPassword': 'Jelszó megerősítése',
    'auth.errors.passwordMismatch': 'A jelszavak nem egyeznek',
    'auth.creatingAccount': 'Fiók létrehozása...',
    'auth.register': 'Regisztráció',
    'auth.haveAccount': 'Már van fiókja?',
    'auth.currentPassword': 'Jelenlegi jelszó',
    'auth.newPassword': 'Új jelszó',
    'auth.address': 'Cím',
    'profile.title': 'Profilom',
    'profile.personalInfo': 'Személyes adatok',
    'profile.saving': 'Mentés...',
    'profile.saveChanges': 'Változtatások mentése',
    'profile.changePassword': 'Jelszó megváltoztatása',
    'profile.updatingPassword': 'Frissítés...',
    'profile.updatePassword': 'Jelszó frissítése',
    'profile.updated': 'Profil sikeresen frissítve.',
    'profile.passwordChanged': 'Jelszó sikeresen megváltoztatva.',
    'dashboard.welcome': 'Üdvözöljük',
    'dashboard.subtitle': 'Kezelje fiókját és rendeléseit',
    'dashboard.profileCard': 'Profilom',
    'dashboard.ordersCard': 'Rendeléseim',
    'dashboard.cartCard': 'Kosaram',
    'dashboard.recentOrders': 'Legutóbbi rendelések',
    'dashboard.orderLabel': 'Rendelés',
    'cart.title': 'Kosár',
    'cart.empty': 'A kosara üres',
    'cart.browseProducts': 'Termékek böngészése',
    'cart.remove': 'Eltávolítás',
    'cart.total': 'Összesen',
    'cart.checkout': 'Fizetés',
    'checkout.title': 'Fizetés',
    'checkout.shippingInfo': 'Szállítási adatok',
    'checkout.fullName': 'Teljes név',
    'checkout.street': 'Cím',
    'checkout.city': 'Város',
    'checkout.state': 'Állam/Tartomány',
    'checkout.zipCode': 'Irányítószám',
    'checkout.country': 'Ország',
    'checkout.placeOrder': 'Megrendelés leadása',
    'checkout.orderSummary': 'Rendelés összegzése',
    'language.fr': 'Francia',
    'language.hu': 'Magyar',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  language = signal<DisplayLanguage>(this.load());

  private load(): DisplayLanguage {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (stored === 'fr' || stored === 'hu') {
      return stored;
    }
    return 'fr';
  }

  setLanguage(value: DisplayLanguage): void {
    this.language.set(value);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, value);
  }

  t(key: string): string {
    return TRANSLATIONS[this.language()]?.[key] ?? key;
  }
}
