apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: artevier
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: {{ (index .Values.services "notification-service").port }}
      targetPort: {{ (index .Values.services "notification-service").targetPort }}
      protocol: TCP