apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: artevier
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - port: {{ (index .Values.services "product-service").port }}
      targetPort: {{ (index .Values.services "product-service").targetPort }}
      protocol: TCP